name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '12 00 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SECRET: ${{ secrets.NEW_SHOW_TELL }}
        run: |
          curl -L https://wa-ncd-sec01.azurewebsites.net/$SECRET

